# Generated by Django 5.2.5 on 2025-08-07 07:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_tag', models.CharField(max_length=100, unique=True)),
                ('make_model', models.CharField(max_length=200)),
                ('cpu_serial_number', models.CharField(max_length=100)),
                ('processor', models.CharField(max_length=100)),
                ('ram', models.CharField(max_length=50)),
                ('hdd', models.CharField(blank=True, max_length=50, null=True)),
                ('ssd', models.CharField(blank=True, max_length=50, null=True)),
                ('os', models.CharField(max_length=100)),
                ('monitor_make_model', models.CharField(blank=True, max_length=200, null=True)),
                ('monitor_serial_number', models.CharField(blank=True, max_length=100, null=True)),
                ('keyboard_mouse', models.CharField(blank=True, max_length=200, null=True)),
                ('ups_make_model', models.CharField(blank=True, max_length=200, null=True)),
                ('ups_serial_number', models.CharField(blank=True, max_length=100, null=True)),
                ('printer_make_model', models.CharField(blank=True, max_length=200, null=True)),
                ('printer_serial_number', models.CharField(blank=True, max_length=100, null=True)),
                ('year_of_purchase', models.PositiveIntegerField()),
                ('condition', models.CharField(choices=[('working', 'Working'), ('damaged', 'Damaged'), ('repair', 'Under Repair'), ('obsolete', 'Obsolete'), ('disposed', 'Disposed')], default='working', max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AssetDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('document', models.FileField(upload_to='asset_documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='assets.asset')),
            ],
        ),
        migrations.CreateModel(
            name='DisposalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disposal_date', models.DateField()),
                ('method', models.CharField(max_length=255)),
                ('certificate', models.FileField(blank=True, null=True, upload_to='disposal_certificates/')),
                ('remarks', models.TextField(blank=True, null=True)),
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='disposal', to='assets.asset')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='asset',
            name='alloted_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.employeeprofile'),
        ),
        migrations.CreateModel(
            name='RepairStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=100)),
                ('date_reported', models.DateField()),
                ('date_resolved', models.DateField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repairs', to='assets.asset')),
            ],
        ),
    ]
